### ISSUE TITLE
Revision de documentacion

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [OlgerAndres/RepositorioAsada#1]
Necesitamos revisar lo que tenemos y definir si estamos listos para continuar con la codificación.

**Comment by kenneth-bolivar-castro** [comment]
Revisar que los ambientes locales se encuentren trabajando al 100% con las mismas configuraciones.

**Comment by OlgerAndres** [comment]
Configuraciones como cuales ,para hacerles la consulta a la asada.

**Comment by OlgerAndres** [comment]
Yo ahora estoy instalando el sql espero que no me de errores, solo eso me faltaria para empezar a programar.

**Comment by kenneth-bolivar-castro** [comment]
Genial

**Comment by kenneth-bolivar-castro** [comment]
Entonces, estamos listos para codificar?

**Comment by OlgerAndres** [comment]
Si listo

**Comment by OlgerAndres** [comment]
A que se refiera con las configuraciones del sistema ?

**Comment by kenneth-bolivar-castro** [comment]
Configuración de las maquinas, mismo IDE misma version del MS SQL server

**Comment by kenneth-bolivar-castro** [comment]
Cerrando este tiquete.
