### ISSUE TITLE
Revisar los formularios

### ISSUE THREAD

**Issue by OlgerAndres** [OlgerAndres/RepositorioAsada#10]
- [x] Revisar que funcione CRUD.
- [x] Crear excepciones.
- [x] Manejo de la cantidad de previstas.
- [x] Validar los grids para que no sean nulos.
- [x] Guardar la cuenta cliente,en configuraciones.
- [x] Mejorar la estética.
- [x] Agregar iconos a los botones.
- [x] Agregar un botón de cancelar las acciones de los formularios
- [x] Formulario "Previstas" mostrar los nombres de "Abonado", "Tarifa" y "Sectores" en lugar de los Ids en el grid.
- [x] Formulario "Previstas" mostrar los nombres completos de los "Abonados" en el "dropdown".

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres @davimontr como estamos aqui?

**Comment by OlgerAndres** [comment]
Se  agregaron nuevas tareas

**Comment by kenneth-bolivar-castro** [comment]
listo
