### ISSUE TITLE
Divide y venceras

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [OlgerAndres/RepositorioAsada#2]
Dividir tareas a realizar para empezar a trabajar en paralelo entre las diferentes capas.

**Comment by OlgerAndres** [comment]
Que parte empiezo

**Comment by kenneth-bolivar-castro** [comment]
Debido a que estas más involucrado con los requerimientos, puedes trabajar con la presentación y logica de negocios, yo me encargo de los datos y la base de datos (procedimiento, triggers, functions, etc)

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres he creado 4 tickets nuevos
- #3 
- #5 
- #6 
- #4 

Para el control global de los avances en las diferentes capas, puedes crear tareas y relacionarlas entre si para dar seguimiento de donde estamos y para donde vamos, sientase libre de agregar los tiquetes que considere necesarios para completar un ticket global.
