### ISSUE TITLE
Capa presentacion

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [OlgerAndres/RepositorioAsada#3]
Vamos a llevar un historico de avances en este ticket para todo lo relacionado con la capa de presentación

**Comment by OlgerAndres** [comment]
Esta bien me parece perfecto.

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres como vamos en esta capa y que tiquetes estan pendientes? para continuar con el desarrollo.

**Comment by OlgerAndres** [comment]
1. Pantalla del Login  y pantalla de control de usuarios.
2. Un menú  o toolbar con los módulos del sistema , se puede añadir información de la ASADA y extras.
3. Pantalla de mantenimiento de abonados y previstas.
4. Pantalla de control de abonados.
5.Pantalla de control de previstas.
6. Pantalla de  reportes.

**Comment by kenneth-bolivar-castro** [comment]
listo
