### ISSUE TITLE
Objetos en la base de datos

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [OlgerAndres/RepositorioAsada#4]
Un ticket global sobre el avance de los objetos en la base de datos.

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres he actualizado la base de datos, por favor restaure el nuevo backup que subí.
Estamos trabajando con el mismo login de UACA, entonces, configurelo igual.

**Comment by OlgerAndres** [comment]
Esta bien compañero apenas llegue a casa ,lo actualizo.

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres los objetos de la base de datos estan listos para trabajar con ellos.

**Comment by kenneth-bolivar-castro** [comment]
listo
