### ISSUE TITLE
Capa de lógica de negocios

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [OlgerAndres/RepositorioAsada#5]
Ticket relacionado con la capa de negocios.

**Comment by OlgerAndres** [comment]
Esta bien @kenneth-bolivar-castro

**Comment by kenneth-bolivar-castro** [comment]
Puedes agregar un @ entonces buscar el nombre de usuario a quien desea referirse, @OlgerAndres 
Puedes hacer ticket entonces dentro de este mismo agrega el comentario y utilizando el # puede buscar el nombre del ticket que hizo para hacer la relacion.

**Comment by OlgerAndres** [comment]
Listo @kenneth-bolivar-castro  👍

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres revise como estoy encriptando la clave:
https://github.com/OlgerAndres/RepositorioAsada/blob/master/Logica/AccionesUsuarios.cs#L34


@kenneth-bolivar-castro 

 System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create();
 Esta parte del código es una referencia que hay que agregar o ya esta por default?

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres que tareas estan pendientes en este tiquete base?
Para continuar trabajando.

@kenneth-bolivar-castro 

1. Usuarios
2. Tarifas
3. Abonados
3. Previstas
4. Sectores

**Comment by OlgerAndres** [comment]
No le entiendo bien el código de encriptacion @kenneth-bolivar-castro

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres es un código para encriptar texto,
`System.Security.Cryptography.MD5`
Donde MD5 es una clase del framework, tienes que implementarlo en el otro proyecto.

**Comment by kenneth-bolivar-castro** [comment]
listo
